from __future__ import annotations
"""
scanner/testers/waf.py
-----------------------
Web Application Firewall (WAF) detection module.

Security concept:
  Knowing whether a WAF is present is critical for pentesters because:
  1. Payloads may be blocked, causing false negatives in other testers
  2. The WAF vendor/type informs bypass strategies
  3. The presence of a WAF is itself a security finding (defence-in-depth)

Detection strategy:
  - Send a benign request and a known-malicious request, compare responses
  - Check response headers for WAF fingerprints (Server, X-*, Set-Cookie)
  - Check response body for WAF block pages
  - Identify specific WAF products by their unique signatures
"""

import logging
import re

from scanner.crawler import CrawledPage
from scanner.reporting.models import Finding, Severity, VulnType
from scanner.testers.base import BaseTester
from scanner.utils import http as http_utils

logger = logging.getLogger(__name__)


# WAF signatures: (name, header_check_fn, body_patterns)
_WAF_SIGNATURES = [
    {
        "name": "Cloudflare",
        "headers": lambda h: (
            "cloudflare" in h.get("Server", "").lower()
            or "cf-ray" in h
            or "__cfduid" in h.get("Set-Cookie", "")
            or "cf-cache-status" in h
        ),
        "body": [r"attention required.*cloudflare", r"ray id:", r"cloudflare"],
    },
    {
        "name": "AWS WAF",
        "headers": lambda h: (
            "awselb" in h.get("Set-Cookie", "").lower()
            or "x-amzn-requestid" in h
            or "x-amz-apigw-id" in h
        ),
        "body": [r"<html>.*403 forbidden.*</html>"],
    },
    {
        "name": "Akamai",
        "headers": lambda h: (
            "akamai" in h.get("Server", "").lower()
            or "x-akamai" in str(h).lower()
            or "akamaighost" in h.get("Server", "").lower()
        ),
        "body": [r"reference.*#\d+\.\w+\.\w+"],
    },
    {
        "name": "ModSecurity",
        "headers": lambda h: (
            "mod_security" in h.get("Server", "").lower()
            or "modsecurity" in h.get("Server", "").lower()
        ),
        "body": [r"mod_security", r"modsecurity", r"not acceptable.*406"],
    },
    {
        "name": "Sucuri",
        "headers": lambda h: (
            "sucuri" in h.get("Server", "").lower()
            or "x-sucuri" in str(h).lower()
        ),
        "body": [r"sucuri website firewall", r"sucuri cloudproxy"],
    },
    {
        "name": "Imperva/Incapsula",
        "headers": lambda h: (
            "incap_ses" in h.get("Set-Cookie", "")
            or "visid_incap" in h.get("Set-Cookie", "")
            or "x-iinfo" in h
            or "x-cdn" in h and "imperva" in h.get("X-CDN", "").lower()
        ),
        "body": [r"incapsula incident id", r"powered by incapsula"],
    },
    {
        "name": "F5 BIG-IP ASM",
        "headers": lambda h: (
            "bigipserver" in h.get("Set-Cookie", "").lower()
            or "x-wa-info" in h
            or "ts" in h.get("Set-Cookie", "").lower() and "bigip" in h.get("Set-Cookie", "").lower()
        ),
        "body": [r"the requested url was rejected"],
    },
    {
        "name": "Barracuda WAF",
        "headers": lambda h: (
            "barra_counter_session" in h.get("Set-Cookie", "")
        ),
        "body": [r"barracuda", r"barracuda_"],
    },
    {
        "name": "Wordfence",
        "headers": lambda h: False,
        "body": [r"wordfence", r"generated by wordfence", r"this response was generated by wordfence"],
    },
    {
        "name": "DenyAll",
        "headers": lambda h: (
            "sessioncookie" in h.get("Set-Cookie", "").lower()
        ),
        "body": [r"conditionblocked"],
    },
    {
        "name": "FortiWeb",
        "headers": lambda h: (
            "fortiwafsid" in h.get("Set-Cookie", "").lower()
        ),
        "body": [r"fortigate", r"fortiweb"],
    },
]

# Generic malicious payload to trigger WAF block pages
_TRIGGER_PAYLOAD = "<script>alert(1)</script>../../etc/passwd' OR 1=1--"


class WAFTester(BaseTester):
    """Detects Web Application Firewall presence and identifies the product."""

    def __init__(self) -> None:
        super().__init__(name="WAF Detector")

    def run(self, pages: list[CrawledPage]) -> list[Finding]:
        self.findings.clear()
        self._params_tested = 0

        if not pages:
            return self.findings

        target_url = pages[0].url
        self._count_test()

        # Step 1: Get a clean baseline response
        try:
            baseline = http_utils.get(target_url)
        except Exception as exc:
            logger.debug("WAF detection baseline request failed: %s", exc)
            return self.findings

        # Step 2: Send a malicious request to trigger WAF
        try:
            sep = "&" if "?" in target_url else "?"
            trigger_url = f"{target_url}{sep}waftest={_TRIGGER_PAYLOAD}"
            trigger_resp = http_utils.get(trigger_url)
        except Exception as exc:
            logger.debug("WAF trigger request failed: %s", exc)
            trigger_resp = None

        # Step 3: Check both responses for WAF signatures
        detected_wafs = set()

        for resp in [baseline, trigger_resp]:
            if resp is None:
                continue
            for sig in _WAF_SIGNATURES:
                waf_name = sig["name"]
                if waf_name in detected_wafs:
                    continue

                # Check headers
                try:
                    if sig["headers"](resp.headers):
                        detected_wafs.add(waf_name)
                        continue
                except Exception:
                    pass

                # Check body patterns
                body_lower = resp.text.lower()
                for pattern in sig["body"]:
                    if re.search(pattern, body_lower, re.IGNORECASE | re.DOTALL):
                        detected_wafs.add(waf_name)
                        break

        # Step 4: Check for generic WAF behaviour (status code change on malicious input)
        generic_waf = False
        if trigger_resp is not None:
            if (baseline.status_code == 200
                    and trigger_resp.status_code in (403, 406, 429, 501)):
                generic_waf = True

        # Report findings
        if detected_wafs:
            waf_list = ", ".join(sorted(detected_wafs))
            finding = Finding(
                vuln_type=VulnType.WAF_DETECTED,
                severity=Severity.LOW,
                url=target_url,
                parameter="(header/response analysis)",
                method="GET",
                payload="(passive fingerprinting + malicious trigger)",
                evidence=(
                    f"Web Application Firewall detected: {waf_list}. "
                    f"Baseline status: {baseline.status_code}, "
                    f"Trigger status: {trigger_resp.status_code if trigger_resp else 'N/A'}. "
                    f"WAF may block attack payloads — other scan results could have false negatives."
                ),
                remediation=(
                    f"WAF detected: {waf_list}. This is an informational finding. "
                    "WAF presence is a positive defence-in-depth measure. Ensure the WAF "
                    "rules are up-to-date and that the application does not solely rely on "
                    "the WAF for security — all input validation should also be done server-side."
                ),
            )
            self._log_finding(finding)
        elif generic_waf:
            finding = Finding(
                vuln_type=VulnType.WAF_DETECTED,
                severity=Severity.LOW,
                url=target_url,
                parameter="(behavioural analysis)",
                method="GET",
                payload=_TRIGGER_PAYLOAD,
                evidence=(
                    f"Generic WAF behaviour detected: baseline returned {baseline.status_code} "
                    f"but malicious payload returned {trigger_resp.status_code}. "
                    f"Could not identify specific WAF product. "
                    f"Other scan results may have false negatives due to WAF blocking."
                ),
                remediation=(
                    "A WAF or request filtering mechanism is active. This is generally positive. "
                    "Ensure the application also validates input server-side and doesn't rely "
                    "solely on the WAF. Keep WAF rules updated."
                ),
            )
            self._log_finding(finding)

        return self.findings
